### ISSUE TITLE
Training Dataset Format

### ISSUE THREAD

**Issue by Dadatata-JZ** [franciszchen/PTree-Net#1]
Hi there, 

Thanks for sharing this interesting work to the community. Regarding the training data formatted in your configs, can you provide some details about what the csv and foremask are used for and how one could obtain or collect this information for reproducing a similar task? 

PS: I understand the confidentiality of the data in your experiment and I just would like to work the usage of them for my convenience to consider on my dataset. 

Thank you in advance.

**Comment by franciszchen** [comment]
Thanks for your interests and sorry for the late response.

For the csv file, each row represents a WSI sample with 'img_name' (the filename to load the sample) and 'score' (her2 score, e.g., 0, 1, 2 and 3), please refer to https://github.com/franciszchen/PTree-Net/blob/5b83cc1d0038cf5875c5b9249deadcfb86e84833/data/dataloader.py#L45-L46.

For the foremask, we threshold the thumbnail in RGB space. The background area is close to white, with high intensity in three channels. This is simple yet effective to generate the foremask, which is stored in .npy file.
